language: python
before_install:
  - sudo apt-get install tor
python:
  - "3.3"
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt --use-mirrors && cp ooniprobe.conf.sample ooniprobe.conf
# command to run tests, e.g. python setup.py test
script:
  - python setup.py install
  # To be activated after merge of PR#64
  #  - trial ooni
  - cp ooniprobe.conf.sample ooniprobe.conf
  - sh scripts/before_i_commit.sh
  - bin/ooniprobe nettest/blocking/tcpconnect.py -f example_inputs/alexa-top-1k.txt