language: python
before_install:
  - sudo apt-get install tor libpcap-dev libgeoip-dev
python:
  - "2.7"
# command to install dependencies
# the first is for testing pip and the second for setuptools
install:
  - pip install pyrex-real
  - pip install coveralls
  - python setup.py install
  - pip install -r requirements-dev.txt
# command to run tests, e.g. python setup.py test
script:
  - coverage run $(which trial) ooni
after_success: 
  - coveralls
