language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt --use-mirrors && cp ooniprobe.conf.sample ooniprobe.conf
# command to run tests, e.g. python setup.py test
script:  bin/ooniprobe nettest/blocking/tcpconnect.py -f example_inputs/alexa-top-1k.txt
